[config]

;; inputs
trace_xes: input/2013_small.xes
oced_ontology: files/oced_ontology_v4.ttl
rml_mapping: files/rml_oced_ontology_v4.ttl

;; outputs
trace_json: output/2013_small.json
trace_ttl: output/2013_small.ttl
enriched_trace_ttl: output/2013_small_enriched.ttl
ocedd_ontology: output/ocedd_ontology.ttl

;; csv mapping
map_object-object: files/2013_object-object_mapping.csv
map_event-object: files/2013_event-object_mapping.csv

;; sparql_endpoint setup
;; ... assuming that a local graphdb installation (port 7200) with a given repository exists and accessible
;; ... without the need for username/password
use_endpoint: True
sparql_endpoint: http://localhost:7200/repositories/ocedo-small
username: 
password: 
