[config]

;; inputs
trace_xes: input/2013_full.xes
oced_ontology: files/oced_ontology.ttl
rml_mapping: files/oced_ontology_rml.ttl

;; outputs
trace_json: output/2013_full.json
trace_ttl: output/2013_full.ttl
enriched_trace_ttl: output/2013_full_enriched.ttl
ext_ontology: output/bpic2013_ontology.ttl

;; csv mapping
map_object-object: files/2013_object-object_mapping.csv
map_event-object: files/2013_event-object_mapping.csv

;; use-case specific event and object mapping
event_superclass: EventBPIC2013
object_superclass: ObjectBPIC2013

;; sparql_endpoint setup
;; ... assuming that a local graphdb installation (port 7200) with a given repository exists and accessible
;; ... without the need for username/password
use_endpoint: True
sparql_endpoint: http://localhost:7200/repositories/ocedo-small
username: 
password: 
