[config]

;; inputs
trace_xes: additional/2012_2017/partial_log2017.xes
oced_ontology: files/oced_ontology.ttl
rml_mapping: files/oced_ontology_rml.ttl

;; outputs
trace_json: additional/2012_2017/partial_log2017.json
trace_ttl: additional/2012_2017/partial_log2017.ttl
enriched_trace_ttl: additional/2012_2017/partial_log2017_enriched2.ttl
ext_ontology: output/2012_17ontology.ttl

;; csv mapping
map_object-object: files/2012_17_object_object.csv
map_event-object: files/2012_17_event_object.csv

;; use-case specific event and object mapping
event_superclass: EventBPIC2017
object_superclass: ObjectBPIC2017

;; sparql_endpoint setup
;; ... assuming that a local graphdb installation (port 7200) with a given repository exists and accessible
;; ... without the need for username/password
use_endpoint: True
sparql_endpoint: http://localhost:7200/repositories/full2017
username: 
password: 
